import Foundation

@main struct ValidationTests {
    static func main() async throws {
        try await MaviTaskChecks.run()
        try DiscordChecks.run()
        func action(_ kind:String = "click", x:Double = 500, text:String = "", key:String = "", direction:String = "", reason:String = "Test") -> NextAction {
            NextAction(kind:kind,reason:reason,x:x,y:500,text:text,key:key,direction:direction,replace:false)
        }
        func rejects(_ value:NextAction) {
            do { try value.validate(); fatalError("Unsafe action was accepted") } catch {}
        }
        try action().validate()
        try action("type",text:"310082.00.02 / 21.25%").validate()
        try action("key",key:"Tab").validate()
        try action("switch",text:"42").validate()
        try action("switch",text:"app:com.apple.finder").validate()
        rejects(action("switch",text:"app:com.example.untrusted"))
        rejects(action(x:1001))
        rejects(action(x:Double.nan))
        rejects(action("shell",text:"arbitrary command"))
        rejects(action("key",key:"Cmd+Space"))
        rejects(action("type",text:"line one\nline two"))
        rejects(action("type",text:String(repeating:"A",count:301)))
        rejects(action("scroll",direction:"invalid"))
        rejects(action("switch",text:"outside listed windows"))
        var inspect = action(); inspect.effect = "inspect"
        assert(inspect.inspectionNavigation)
        var edit = action(); edit.effect = "edit"
        assert(!edit.inspectionNavigation)
        var typing = action("type",text:"example"); typing.effect = "inspect"
        assert(!typing.inspectionNavigation)
        var enter = action("key",key:"Enter"); enter.effect = "inspect"
        assert(!enter.inspectionNavigation)
        assert(!action().inspectionNavigation)
        await MainActor.run {
            assert(UnifiedAgent.fallbackRoute("Generate an image of a mountain lake") == "image")
            assert(UnifiedAgent.fallbackRoute("Analyze this stock filing") == "stocks")
            assert(UnifiedAgent.fallbackRoute("What is the capital of France?") == "chat")
            assert(UnifiedAgent.isDiscordStatusRequest("Can you make sure my Discord connection is good?"))
            assert(UnifiedAgent.explicitRoute("Can you make sure my Discord connection is good?") == "chat")
            assert(UnifiedAgent.explicitRoute("Create a Word doc about my trip itinerary") == "files")
            assert(UnifiedAgent.explicitRoute("Make an XLSX budget workbook with rent and food totals") == "files")
            assert(UnifiedAgent.explicitRoute("Create slides for the project update") == "files")
            assert(UnifiedAgent.explicitRoute("How do I create a Word document?") == nil)
            assert(UnifiedAgent.explicitRoute("Do not create a PDF") == nil)
            assert(UnifiedAgent.explicitRoute("I don't want to create a Word doc") == nil)
            assert(UnifiedAgent.explicitRoute("I want to learn how to create a Word doc") == nil)
            assert(UnifiedAgent.explicitRoute("Explain the phrase \"create a Word doc\"") == nil)
            assert(UnifiedAgent.fallbackRoute("How do I create a Word document?") == "chat")
            assert(UnifiedAgent.explicitRoute("Open https://example.com in the browser") == "browser")
            assert(UnifiedAgent.explicitAppTarget("Open Brave")?.bundleID == "com.brave.Browser")
            assert(UnifiedAgent.explicitAppTarget("I use Chrome for work") == nil)
            assert(UnifiedAgent.explicitAppTarget("Make a Word doc about how to use Brave") == nil)
            assert(UnifiedAgent.explicitAppTarget("Do not want to open Chrome") == nil)
            assert(UnifiedAgent.explicitAppTarget("Open Brave and Chrome") == nil)
            assert(UnifiedAgent.explicitAppTargets("Open Brave and Chrome").count == 2)
            assert(UnifiedAgent.explicitRoute("Make a Word doc about how to use Brave") == "files")
            assert(!UnifiedAgent.needsWindowControl("Open Chrome"))
            assert(UnifiedAgent.needsWindowControl("Work in the Webex meeting"))
            assert(Desk.allowsWindowSwitch(scope:"singleApp",sourceBundleID:"com.apple.finder",destinationBundleID:"com.apple.finder"))
            assert(!Desk.allowsWindowSwitch(scope:"singleApp",sourceBundleID:"com.apple.finder",destinationBundleID:"com.microsoft.Word"))
            assert(Desk.allowsWindowSwitch(scope:"wholeComputer",sourceBundleID:"com.apple.finder",destinationBundleID:"com.microsoft.Word"))
            assert(!Desk.allowsWindowSwitch(scope:"wholeComputer",sourceBundleID:"com.apple.finder",destinationBundleID:nil))
            assert(!Desk.allowsWindowSwitch(scope:"wholeComputer",sourceBundleID:"com.apple.finder",destinationBundleID:""))
            assert(Desk.isLaunchableBundleID("com.apple.finder"))
            assert(Desk.isLaunchableBundleID("com.microsoft.Word"))
            assert(!Desk.isLaunchableBundleID("com.example.untrusted"))
            assert(UnifiedAgent.explicitAppTarget("Open Finder")?.bundleID == "com.apple.finder")
            assert(UnifiedAgent.explicitAppTarget("Open Microsoft Word")?.bundleID == "com.microsoft.Word")
            assert(UnifiedAgent.explicitAppTarget("Open Chrome and go to https://example.com")?.bundleID == "com.google.Chrome")
            assert(UnifiedAgent.explicitAppTarget("Work in the Webex meeting")?.bundleID == "Cisco-Systems.Spark")
            assert(UnifiedAgent.explicitRoute("Open Webex") == "computer")
            assert(UnifiedAgent.explicitAppTarget("How do I open Webex?") == nil)
            assert(UnifiedAgent.explicitAppTarget("Do not open Chrome") == nil)
            assert(UnifiedAgent.explicitAppTarget("Explain the phrase \"open Chrome\"") == nil)
            assert(UnifiedAgent.bareLinkURL("https://example.com") == "https://example.com")
            assert(UnifiedAgent.bareLinkURL("open https://example.com") == "https://example.com")
            assert(UnifiedAgent.bareLinkURL("https://example.com.") == "https://example.com")
            assert(UnifiedAgent.bareLinkURL("Summarize https://example.com") == nil)
            assert(UnifiedAgent.explicitRoute("Please control my computer and click the button") == "computer")
            assert(UnifiedAgent.fallbackRoute("Please control my computer and click the button") == "computer")
            assert(UnifiedAgent.explicitRoute("What does computer vision mean?") == nil)
            assert(UnifiedAgent.explicitRoute("Is Discord good?") == nil)
            assert(UnifiedAgent.explicitRoute("Can you click that for me?") == "computer")
            assert(!Desk.requiresManualReview(request:"Open the settings page"))
            assert(Desk.requiresManualReview(request:"Send this email"))
            assert(Desk.requiresManualReview(request:"Review the account security settings"))
            assert(Desk.requiresManualReview(request:"Open the page", action: action(reason:"Click Delete")))
            var routineClick = action(reason:"Open the settings tab"); routineClick.effect = "inspect"
            assert(routineClick.routineNavigation)
            var suspiciousClick = action(reason:"Click Save"); suspiciousClick.effect = "inspect"
            assert(!suspiciousClick.routineNavigation)
            assert(DesignAdvisor.shouldConsult("Design a logo for my bakery"))
            assert(DesignAdvisor.shouldConsult("Design a trading dashboard with clear risk hierarchy"))
            assert(DesignAdvisor.shouldConsult("Review the UI design for my cascade layout"))
            assert(!DesignAdvisor.shouldConsult("Create a 3D model in OpenSCAD"))
            assert(!DesignAdvisor.shouldConsult("Design a research plan for the market outlook"))
            assert(!DesignAdvisor.shouldConsult("Analyze this stock filing"))
            let directMaviRequest = "i need you to edidt yourself let the users also be able to pick their accent color like same as you have also instead of some bulky squre elements i want softer more comfortable ui"
            let directMaviPlan = UnifiedPlanning.directMaviUpdatePlan(directMaviRequest)
            assert(directMaviPlan?.kind == "update")
            assert(directMaviPlan?.task == directMaviRequest)
            assert(UnifiedAgent.fallbackRoute(directMaviRequest) == "update")
            assert(UnifiedPlanning.requestsVisualAdvice(directMaviRequest))
            assert(UnifiedPlanning.directMaviUpdatePlan("Can you edit yourself?") == nil)
            assert(UnifiedPlanning.directMaviUpdatePlan("Can you edit yourself without changing anything?") == nil)
            assert(UnifiedPlanning.directMaviUpdatePlan("Do not edit yourself" ) == nil)
            assert(UnifiedPlanning.directMaviUpdatePlan("Don't change your UI" ) == nil)
            assert(UnifiedPlanning.directMaviUpdatePlan("Tell me about editing yourself") == nil)
            assert(UnifiedPlanning.directMaviUpdatePlan("A user said: \"edit yourself\"; explain what they mean") == nil)
            assert(UnifiedPlanning.directMaviUpdatePlan("Please edit our React app's accent picker") == nil)
            assert(UnifiedPlanning.directMaviUpdatePlan("Edit my external app, Mavi") == nil)
            assert(UnifiedPlanning.directMaviUpdatePlan("Can you edit yourself to let users pick an accent color?")?.kind == "update")
            let fleet = AgentFleet()
            let failedJob = fleet.begin(role:"Verifier",model:"gemma4:12b",assignment:"Check a bounded response")
            fleet.update(failedJob,state:"failed",detail:"Synthetic failure")
            assert(fleet.jobs.first(where:{$0.id == failedJob})?.finished != nil)
            let activeJobs = (0..<61).map { fleet.begin(role:"Worker",model:"test",assignment:"Active \($0)") }
            assert(activeJobs.allSatisfy { id in fleet.jobs.contains(where:{$0.id == id && $0.state == "running"}) })
            fleet.stopActive()
            assert(activeJobs.allSatisfy { id in fleet.jobs.contains(where:{$0.id == id && $0.state == "stopped" && $0.finished != nil}) })
            assert(Desk.localCalculation("What is 17 times 23?") == "391")
            assert(Desk.localCalculation("0.1 + 0.2") == "0.3")
            assert(Desk.localCalculation("5 / 0") == "Division by zero is undefined.")
            assert(Desk.localCalculation("Transfer 5 + 2 dollars") == nil)
            assert(Desk.localCalculation("3 + 4 * 5") == nil)
            let groupedFleet=AgentFleet()
            let router=groupedFleet.begin(role:"Jev router",model:"test",assignment:"Route task")
            let lead=groupedFleet.begin(role:"Lead responder",model:"test",assignment:"Prepare response")
            let worker=groupedFleet.begin(role:"Independent verifier",model:"test",assignment:"Check response")
            assert(groupedFleet.jobs.first(where:{$0.id == lead})?.parentID == router)
            assert(groupedFleet.jobs.first(where:{$0.id == worker})?.parentID == lead)
            assert(groupedFleet.taskGroups.count == 1)
            assert(ProgressNarrator.candidates(for:groupedFleet.jobs).allSatisfy{!$0.contains("finished")})
            groupedFleet.update(worker,state:"waiting",detail:"Need input")
            assert(ProgressNarrator.candidates(for:groupedFleet.jobs).first?.contains("paused") == true)
            _=groupedFleet.begin(role:"Jev router",model:"test",assignment:"New task")
            assert(groupedFleet.taskGroups.count == 2)
            let desk = Desk()
            let browser=BrowserState(),control=Pipe()
            assert(browser.useExistingBrowser)
            browser.input=control;browser.busy=true
            browser.event(Data(#"{"type":"review","request_id":"question-7","kind":"question","text":"Which account should I use?"}"#.utf8))
            assert(browser.reviewPrompt?.requestID == "question-7")
            assert(browser.respond(text:"Work account"))
            assert(browser.review && browser.responding)
            try? control.fileHandleForWriting.close()
            let response=(try? JSONSerialization.jsonObject(with:control.fileHandleForReading.readToEnd() ?? Data())) as? [String:Any]
            assert(response?["command"] as? String == "respond")
            assert(response?["request_id"] as? String == "question-7")
            assert(response?["text"] as? String == "Work account")
            assert(response?["approved"] as? Bool == true)
            browser.stop()
            assert(browser.reviewPrompt == nil && !browser.busy)
            assert(desk.cachedImageModel("AbstractFramework/qwen-image-edit-2511-4bit"))
            assert(!desk.cachedImageModel("AbstractFramework/model-not-installed"))
            let folder = FileManager.default.temporaryDirectory.appendingPathComponent("mavi-history-test-" + UUID().uuidString)
            defer { try? FileManager.default.removeItem(at:folder) }
            desk.persistenceRootOverride = folder
            desk.add("You","A searchable test conversation")
            desk.add("Fast Qwen","A locally stored response")
            let firstID = desk.currentConversationID
            let messageIDs = desk.lines.map(\.id)
            assert(desk.conversations.count == 1)
            desk.reset()
            desk.add("You","Second conversation")
            assert(desk.conversations.count == 2)
            let reloaded = Desk(); reloaded.persistenceRootOverride = folder; reloaded.loadConversations()
            assert(reloaded.conversations.count == 2)
            reloaded.openConversation(reloaded.conversations.first(where:{$0.id == firstID})!)
            assert(reloaded.lines.map(\.id) == messageIDs)
            reloaded.busy = true; reloaded.deleteConversation(firstID)
            assert(reloaded.conversations.count == 2)
            reloaded.busy = false; reloaded.deleteConversation(firstID)
            assert(reloaded.lines.isEmpty)
            assert(!FileManager.default.fileExists(atPath:reloaded.chatsURL.appendingPathComponent(firstID.uuidString + ".json").path))
            reloaded.deleteAllConversations(); reloaded.loadConversations()
            assert(reloaded.conversations.isEmpty)
            assert(!FileManager.default.fileExists(atPath:reloaded.chatsURL.path))
            let event = desk.beginActivity("router",model:"test",detail:"test decision")
            desk.finishActivity(event,detail:"complete")
            assert(desk.activities.last?.tokensReported == false)
            assert(desk.activities.last?.state == "complete")
            let failed = desk.beginActivity("fast",model:"test",detail:"failed request")
            desk.failUnfinishedActivity(failed)
            assert(desk.activities.last?.state == "failed")
        }
        await MainActor.run {
            let fleet=AgentFleet()
            let completed=fleet.begin(role:"Planner",model:"test",assignment:"Plan")
            fleet.finish(completed,detail:"Done")
            fleet.update(completed,state:"stopped",detail:"Later worker stopped")
            assert(fleet.jobs.first?.state == "complete")
        }
        print("PASS: action validation, chat persistence and stable IDs, reopening, busy deletion guards, individual/all deletion, and activity status checks.")
    }
}
